"""The README status table stays in step with ``project-status.yaml``.

The manifest is the single source of truth — a portfolio dashboard reads it, so
it gets updated. The README duplicated it by hand and drifted: for three weeks it
claimed the learner runtime did not exist, weeks after it shipped. The table is
now generated by ``scripts/render_status.py`` and these tests fail if the
committed README no longer matches, so the drift cannot reach main.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from render_status import (  # noqa: E402  (import needs the path above)
    BEGIN,
    END,
    STATUS_CELLS,
    load_features,
    render_block,
    replace_block,
)


class TestManifest:
    """``project-status.yaml`` is well formed."""

    def test_loads_and_validates(self) -> None:
        """Every feature has an id, a name, and a known status."""
        features = load_features()
        assert features, "the manifest declares no features"
        for feature in features:
            assert feature["status"] in STATUS_CELLS

    def test_ids_are_unique(self) -> None:
        ids = [f["id"] for f in load_features()]
        assert len(ids) == len(set(ids)), "duplicate feature id in project-status.yaml"

    @pytest.mark.parametrize("status", sorted(STATUS_CELLS))
    def test_every_status_renders_a_cell(self, status: str) -> None:
        """A status the renderer cannot map would silently blank a cell."""
        assert STATUS_CELLS[status].strip()


class TestReadmeTableIsGenerated:
    """The committed README matches what the generator produces."""

    def test_readme_has_the_markers(self) -> None:
        text = (ROOT / "README.md").read_text(encoding="utf-8")
        assert BEGIN in text and END in text, (
            "README lost the generated-status markers; scripts/render_status.py "
            "cannot find the block to replace."
        )

    def test_readme_matches_the_manifest(self) -> None:
        """Editing the manifest without running `make status` fails here."""
        current = (ROOT / "README.md").read_text(encoding="utf-8")
        expected = replace_block(current, render_block(load_features()))
        assert current == expected, (
            "README status table is out of date with project-status.yaml. "
            "Run `make status` and commit the result."
        )

    def test_every_feature_appears(self) -> None:
        """No feature is silently dropped between manifest and README."""
        current = (ROOT / "README.md").read_text(encoding="utf-8")
        block = current[current.find(BEGIN) : current.find(END)]
        missing = [f["name"] for f in load_features() if f["name"] not in block]
        assert not missing, f"features absent from the README table: {missing}"
